"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
fix issue: #74 https://github.com/so1n/protobuf_to_pydantic/issues/74"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ReportData(google.protobuf.message.Message):
    """Annotations are used in runtime mode
    p2p: {"oneof:data": {"required": true}}
    p2p: {"oneof:data": {"oneof_extend": {"optional": ["location_value"]}}}
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOCATION_VALUE_FIELD_NUMBER: builtins.int
    TIME_VALUE_FIELD_NUMBER: builtins.int
    @property
    def location_value(self) -> global___GeoLocation: ...
    @property
    def time_value(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        location_value: global___GeoLocation | None = ...,
        time_value: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data", "location_value", b"location_value", "time_value", b"time_value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "location_value", b"location_value", "time_value", b"time_value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["data", b"data"]) -> typing.Literal["location_value", "time_value"] | None: ...

global___ReportData = ReportData

@typing.final
class GeoLocation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LATITUDE_FIELD_NUMBER: builtins.int
    LONGITUDE_FIELD_NUMBER: builtins.int
    ALTITUDE_METERS_FIELD_NUMBER: builtins.int
    latitude: builtins.float
    longitude: builtins.float
    altitude_meters: builtins.float
    def __init__(
        self,
        *,
        latitude: builtins.float = ...,
        longitude: builtins.float = ...,
        altitude_meters: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_altitude_meters", b"_altitude_meters", "altitude_meters", b"altitude_meters"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_altitude_meters", b"_altitude_meters", "altitude_meters", b"altitude_meters", "latitude", b"latitude", "longitude", b"longitude"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_altitude_meters", b"_altitude_meters"]) -> typing.Literal["altitude_meters"] | None: ...

global___GeoLocation = GeoLocation

@typing.final
class Report(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SOURCE_ID_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    source_id: builtins.str
    @property
    def data(self) -> global___ReportData: ...
    def __init__(
        self,
        *,
        source_id: builtins.str | None = ...,
        data: global___ReportData | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_source_id", b"_source_id", "data", b"data", "source_id", b"source_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_source_id", b"_source_id", "data", b"data", "source_id", b"source_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_source_id", b"_source_id"]) -> typing.Literal["source_id"] | None: ...

global___Report = Report
