"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import example.example_proto.demo.diff_pkg_refer_1_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Demo2(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MyFieldEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> example.example_proto.demo.diff_pkg_refer_1_pb2.Demo1: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: example.example_proto.demo.diff_pkg_refer_1_pb2.Demo1 | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    MYFIELD_FIELD_NUMBER: builtins.int
    @property
    def myField(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, example.example_proto.demo.diff_pkg_refer_1_pb2.Demo1]: ...
    def __init__(
        self,
        *,
        myField: collections.abc.Mapping[builtins.str, example.example_proto.demo.diff_pkg_refer_1_pb2.Demo1] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["myField", b"myField"]) -> None: ...

global___Demo2 = Demo2
