# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example/example_proto/demo/value_demo.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'example/example_proto/demo/value_demo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+example/example_proto/demo/value_demo.proto\x12\x0c\x65xample.demo\x1a\x1cgoogle/protobuf/struct.proto\"\x83\x02\n\x10ValueTestMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12-\n\rdynamic_value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value\x12*\n\nvalue_list\x18\x03 \x03(\x0b\x32\x16.google.protobuf.Value\x12?\n\tvalue_map\x18\x04 \x03(\x0b\x32,.example.demo.ValueTestMessage.ValueMapEntry\x1aG\n\rValueMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.example_proto.demo.value_demo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALUETESTMESSAGE_VALUEMAPENTRY']._loaded_options = None
  _globals['_VALUETESTMESSAGE_VALUEMAPENTRY']._serialized_options = b'8\001'
  _globals['_VALUETESTMESSAGE']._serialized_start=92
  _globals['_VALUETESTMESSAGE']._serialized_end=351
  _globals['_VALUETESTMESSAGE_VALUEMAPENTRY']._serialized_start=280
  _globals['_VALUETESTMESSAGE_VALUEMAPENTRY']._serialized_end=351
# @@protoc_insertion_point(module_scope)
