"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.struct_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ValueTestMessage(google.protobuf.message.Message):
    """Test message with google.protobuf.Value field"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class ValueMapEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text
        @property
        def value(self) -> google.protobuf.struct_pb2.Value: ...
        def __init__(self,
            *,
            key: typing.Text = ...,
            value: typing.Optional[google.protobuf.struct_pb2.Value] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    DYNAMIC_VALUE_FIELD_NUMBER: builtins.int
    VALUE_LIST_FIELD_NUMBER: builtins.int
    VALUE_MAP_FIELD_NUMBER: builtins.int
    id: typing.Text
    @property
    def dynamic_value(self) -> google.protobuf.struct_pb2.Value: ...
    @property
    def value_list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Value]: ...
    @property
    def value_map(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, google.protobuf.struct_pb2.Value]: ...
    def __init__(self,
        *,
        id: typing.Text = ...,
        dynamic_value: typing.Optional[google.protobuf.struct_pb2.Value] = ...,
        value_list: typing.Optional[typing.Iterable[google.protobuf.struct_pb2.Value]] = ...,
        value_map: typing.Optional[typing.Mapping[typing.Text, google.protobuf.struct_pb2.Value]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["dynamic_value",b"dynamic_value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["dynamic_value",b"dynamic_value","id",b"id","value_list",b"value_list","value_map",b"value_map"]) -> None: ...
global___ValueTestMessage = ValueTestMessage
