"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.struct_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ValueTestMessage(google.protobuf.message.Message):
    """Test message with google.protobuf.Value field"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ValueMapEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> google.protobuf.struct_pb2.Value: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: google.protobuf.struct_pb2.Value | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    DYNAMIC_VALUE_FIELD_NUMBER: builtins.int
    VALUE_LIST_FIELD_NUMBER: builtins.int
    VALUE_MAP_FIELD_NUMBER: builtins.int
    id: builtins.str
    @property
    def dynamic_value(self) -> google.protobuf.struct_pb2.Value: ...
    @property
    def value_list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Value]: ...
    @property
    def value_map(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, google.protobuf.struct_pb2.Value]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        dynamic_value: google.protobuf.struct_pb2.Value | None = ...,
        value_list: collections.abc.Iterable[google.protobuf.struct_pb2.Value] | None = ...,
        value_map: collections.abc.Mapping[builtins.str, google.protobuf.struct_pb2.Value] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_dynamic_value", b"_dynamic_value", "dynamic_value", b"dynamic_value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_dynamic_value", b"_dynamic_value", "dynamic_value", b"dynamic_value", "id", b"id", "value_list", b"value_list", "value_map", b"value_map"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_dynamic_value", b"_dynamic_value"]) -> typing.Literal["dynamic_value"] | None: ...

global___ValueTestMessage = ValueTestMessage
