"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class WellKnownTypesMessage(google.protobuf.message.Message):
    """Message to test well-known protobuf types for round-trip conversion"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class TimestampMapEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text
        @property
        def value(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        def __init__(self,
            *,
            key: typing.Text = ...,
            value: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    class DurationMapEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text
        @property
        def value(self) -> google.protobuf.duration_pb2.Duration: ...
        def __init__(self,
            *,
            key: typing.Text = ...,
            value: typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    EXPIRES_AT_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    PROCESSING_TIME_FIELD_NUMBER: builtins.int
    TTL_FIELD_NUMBER: builtins.int
    OPTIONAL_TIMESTAMP_FIELD_NUMBER: builtins.int
    OPTIONAL_DURATION_FIELD_NUMBER: builtins.int
    EVENT_TIMESTAMPS_FIELD_NUMBER: builtins.int
    INTERVALS_FIELD_NUMBER: builtins.int
    TIMESTAMP_MAP_FIELD_NUMBER: builtins.int
    DURATION_MAP_FIELD_NUMBER: builtins.int
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp fields"""
        pass
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def expires_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def timeout(self) -> google.protobuf.duration_pb2.Duration:
        """Duration fields"""
        pass
    @property
    def processing_time(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def ttl(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def optional_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Optional well-known types"""
        pass
    @property
    def optional_duration(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def event_timestamps(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.timestamp_pb2.Timestamp]:
        """Repeated well-known types"""
        pass
    @property
    def intervals(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.duration_pb2.Duration]: ...
    @property
    def timestamp_map(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, google.protobuf.timestamp_pb2.Timestamp]:
        """Map with well-known types as values"""
        pass
    @property
    def duration_map(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, google.protobuf.duration_pb2.Duration]: ...
    def __init__(self,
        *,
        created_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        updated_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        expires_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        timeout: typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        processing_time: typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        ttl: typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        optional_timestamp: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        optional_duration: typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        event_timestamps: typing.Optional[typing.Iterable[google.protobuf.timestamp_pb2.Timestamp]] = ...,
        intervals: typing.Optional[typing.Iterable[google.protobuf.duration_pb2.Duration]] = ...,
        timestamp_map: typing.Optional[typing.Mapping[typing.Text, google.protobuf.timestamp_pb2.Timestamp]] = ...,
        duration_map: typing.Optional[typing.Mapping[typing.Text, google.protobuf.duration_pb2.Duration]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_optional_duration",b"_optional_duration","_optional_timestamp",b"_optional_timestamp","created_at",b"created_at","expires_at",b"expires_at","optional_duration",b"optional_duration","optional_timestamp",b"optional_timestamp","processing_time",b"processing_time","timeout",b"timeout","ttl",b"ttl","updated_at",b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_optional_duration",b"_optional_duration","_optional_timestamp",b"_optional_timestamp","created_at",b"created_at","duration_map",b"duration_map","event_timestamps",b"event_timestamps","expires_at",b"expires_at","intervals",b"intervals","optional_duration",b"optional_duration","optional_timestamp",b"optional_timestamp","processing_time",b"processing_time","timeout",b"timeout","timestamp_map",b"timestamp_map","ttl",b"ttl","updated_at",b"updated_at"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_optional_duration",b"_optional_duration"]) -> typing.Optional[typing_extensions.Literal["optional_duration"]]: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_optional_timestamp",b"_optional_timestamp"]) -> typing.Optional[typing_extensions.Literal["optional_timestamp"]]: ...
global___WellKnownTypesMessage = WellKnownTypesMessage

class WellKnownEdgeCasesMessage(google.protobuf.message.Message):
    """Edge cases for well-known types"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ZERO_TIMESTAMP_FIELD_NUMBER: builtins.int
    ZERO_DURATION_FIELD_NUMBER: builtins.int
    MAX_TIMESTAMP_FIELD_NUMBER: builtins.int
    MAX_DURATION_FIELD_NUMBER: builtins.int
    NEGATIVE_DURATION_FIELD_NUMBER: builtins.int
    PRECISE_TIMESTAMP_FIELD_NUMBER: builtins.int
    PRECISE_DURATION_FIELD_NUMBER: builtins.int
    @property
    def zero_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Zero values"""
        pass
    @property
    def zero_duration(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def max_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Max values"""
        pass
    @property
    def max_duration(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def negative_duration(self) -> google.protobuf.duration_pb2.Duration:
        """Negative duration (durations can be negative)"""
        pass
    @property
    def precise_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp with nanosecond precision"""
        pass
    @property
    def precise_duration(self) -> google.protobuf.duration_pb2.Duration:
        """Duration with nanosecond precision"""
        pass
    def __init__(self,
        *,
        zero_timestamp: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        zero_duration: typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        max_timestamp: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        max_duration: typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        negative_duration: typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        precise_timestamp: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        precise_duration: typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["max_duration",b"max_duration","max_timestamp",b"max_timestamp","negative_duration",b"negative_duration","precise_duration",b"precise_duration","precise_timestamp",b"precise_timestamp","zero_duration",b"zero_duration","zero_timestamp",b"zero_timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["max_duration",b"max_duration","max_timestamp",b"max_timestamp","negative_duration",b"negative_duration","precise_duration",b"precise_duration","precise_timestamp",b"precise_timestamp","zero_duration",b"zero_duration","zero_timestamp",b"zero_timestamp"]) -> None: ...
global___WellKnownEdgeCasesMessage = WellKnownEdgeCasesMessage
