"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class WellKnownTypesMessage(google.protobuf.message.Message):
    """Message to test well-known protobuf types for round-trip conversion"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TimestampMapEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class DurationMapEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> google.protobuf.duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: google.protobuf.duration_pb2.Duration | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    EXPIRES_AT_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    PROCESSING_TIME_FIELD_NUMBER: builtins.int
    TTL_FIELD_NUMBER: builtins.int
    OPTIONAL_TIMESTAMP_FIELD_NUMBER: builtins.int
    OPTIONAL_DURATION_FIELD_NUMBER: builtins.int
    EVENT_TIMESTAMPS_FIELD_NUMBER: builtins.int
    INTERVALS_FIELD_NUMBER: builtins.int
    TIMESTAMP_MAP_FIELD_NUMBER: builtins.int
    DURATION_MAP_FIELD_NUMBER: builtins.int
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp fields"""

    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def expires_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def timeout(self) -> google.protobuf.duration_pb2.Duration:
        """Duration fields"""

    @property
    def processing_time(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def ttl(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def optional_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Optional well-known types"""

    @property
    def optional_duration(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def event_timestamps(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.timestamp_pb2.Timestamp]:
        """Repeated well-known types"""

    @property
    def intervals(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.duration_pb2.Duration]: ...
    @property
    def timestamp_map(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, google.protobuf.timestamp_pb2.Timestamp]:
        """Map with well-known types as values"""

    @property
    def duration_map(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, google.protobuf.duration_pb2.Duration]: ...
    def __init__(
        self,
        *,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        expires_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        timeout: google.protobuf.duration_pb2.Duration | None = ...,
        processing_time: google.protobuf.duration_pb2.Duration | None = ...,
        ttl: google.protobuf.duration_pb2.Duration | None = ...,
        optional_timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        optional_duration: google.protobuf.duration_pb2.Duration | None = ...,
        event_timestamps: collections.abc.Iterable[google.protobuf.timestamp_pb2.Timestamp] | None = ...,
        intervals: collections.abc.Iterable[google.protobuf.duration_pb2.Duration] | None = ...,
        timestamp_map: collections.abc.Mapping[builtins.str, google.protobuf.timestamp_pb2.Timestamp] | None = ...,
        duration_map: collections.abc.Mapping[builtins.str, google.protobuf.duration_pb2.Duration] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_optional_duration", b"_optional_duration", "_optional_timestamp", b"_optional_timestamp", "created_at", b"created_at", "expires_at", b"expires_at", "optional_duration", b"optional_duration", "optional_timestamp", b"optional_timestamp", "processing_time", b"processing_time", "timeout", b"timeout", "ttl", b"ttl", "updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_optional_duration", b"_optional_duration", "_optional_timestamp", b"_optional_timestamp", "created_at", b"created_at", "duration_map", b"duration_map", "event_timestamps", b"event_timestamps", "expires_at", b"expires_at", "intervals", b"intervals", "optional_duration", b"optional_duration", "optional_timestamp", b"optional_timestamp", "processing_time", b"processing_time", "timeout", b"timeout", "timestamp_map", b"timestamp_map", "ttl", b"ttl", "updated_at", b"updated_at"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_optional_duration", b"_optional_duration"]) -> typing.Literal["optional_duration"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_optional_timestamp", b"_optional_timestamp"]) -> typing.Literal["optional_timestamp"] | None: ...

global___WellKnownTypesMessage = WellKnownTypesMessage

@typing.final
class WellKnownEdgeCasesMessage(google.protobuf.message.Message):
    """Edge cases for well-known types"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ZERO_TIMESTAMP_FIELD_NUMBER: builtins.int
    ZERO_DURATION_FIELD_NUMBER: builtins.int
    MAX_TIMESTAMP_FIELD_NUMBER: builtins.int
    MAX_DURATION_FIELD_NUMBER: builtins.int
    NEGATIVE_DURATION_FIELD_NUMBER: builtins.int
    PRECISE_TIMESTAMP_FIELD_NUMBER: builtins.int
    PRECISE_DURATION_FIELD_NUMBER: builtins.int
    @property
    def zero_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Zero values"""

    @property
    def zero_duration(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def max_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Max values"""

    @property
    def max_duration(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def negative_duration(self) -> google.protobuf.duration_pb2.Duration:
        """Negative duration (durations can be negative)"""

    @property
    def precise_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp with nanosecond precision"""

    @property
    def precise_duration(self) -> google.protobuf.duration_pb2.Duration:
        """Duration with nanosecond precision"""

    def __init__(
        self,
        *,
        zero_timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        zero_duration: google.protobuf.duration_pb2.Duration | None = ...,
        max_timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        max_duration: google.protobuf.duration_pb2.Duration | None = ...,
        negative_duration: google.protobuf.duration_pb2.Duration | None = ...,
        precise_timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        precise_duration: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["max_duration", b"max_duration", "max_timestamp", b"max_timestamp", "negative_duration", b"negative_duration", "precise_duration", b"precise_duration", "precise_timestamp", b"precise_timestamp", "zero_duration", b"zero_duration", "zero_timestamp", b"zero_timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["max_duration", b"max_duration", "max_timestamp", b"max_timestamp", "negative_duration", b"negative_duration", "precise_duration", b"precise_duration", "precise_timestamp", b"precise_timestamp", "zero_duration", b"zero_duration", "zero_timestamp", b"zero_timestamp"]) -> None: ...

global___WellKnownEdgeCasesMessage = WellKnownEdgeCasesMessage
